apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rzert5giq-nodejs-gitops
  description: This is GitOps manifest for rzert5giq-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=rzert5giq-nodejs
    backstage.io/kubernetes-id: rzert5giq-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rzert5giq-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rzert5giq-nodejs
