apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rzert5giq-nodejs
  janus-idp.io/tekton: rzert5giq-nodejs
  backstage.io/kubernetes-id: rzert5giq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rzert5giq-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
